apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    method: methodistalsoeinlabel
    another: label
  name: nginx-yaml-minimal-pod-definition
spec:
  containers:
  - image: nginx
    name: nginx
