apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: strelok-app
  name: strelok-app
  namespace: strelok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strelok-app
  template:
    metadata:
      labels:
        app: strelok-app
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie:v3.16.0
        name: mealie
        ports:
          - containerPort: 9000
