apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: strelok-app
  name: strelok-app
  namespace: strelok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strelok-app
  template:
    metadata:
      labels:
        app: strelok-app
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie:v3.16.0
        name: mealie
        ports:
          - containerPort: 9000

---
apiVersion: v1              # Kubernetes API-Version für Core-Objekte (Service, Pod etc.)
kind: Service               # Objekttyp: Service
metadata:
  name: strelok-app-service # Name des Services im Cluster
  namespace: strelok        # In welchem Namespace der Service lebt
spec:
  selector:
    app: strelok-app        # Verbindet sich mit Pods die dieses Label haben
  ports:
    - protocol: TCP         # Netzwerkprotokoll
      port: 80              # Port auf dem der Service intern im Cluster lauscht
      targetPort: 9000      # Port auf dem der Container lauscht (Mealie)
      nodePort: 30925       # Externer Port über den die App erreichbar ist (localhost:30925)
  type: NodePort            # Kein Cloud-Provider nötig, erreichbar direkt über localhost:nodePort
